//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartagenaGame.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameResult
    {
        public int Id { get; set; }
        public int WinnerPlayerId { get; set; }
        public System.DateTime FinishedDateTime { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
