//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime LockedUntil { get; set; }
        public bool IsPremium { get; set; }
        public bool IsInactive { get; set; }
        public string NotificationSettings { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual AccountStatistic AccountStatistic { get; set; }
    }
}
