//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountStatistic
    {
        public int Id { get; set; }
        public int TimeOnline { get; set; }
        public int GewonnenGames { get; set; }
        public System.DateTime TimeLoggedIn { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
