//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User.BU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserModelContainer : DbContext
    {
        public UserModelContainer()
            : base("name=UserModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> AccountSet { get; set; }
        public virtual DbSet<Profile> ProfileSet { get; set; }
        public virtual DbSet<AccountStatistic> AccountStatisticSet { get; set; }
        public virtual DbSet<Notification> NotificationSet { get; set; }
        public virtual DbSet<Report> ReportSet { get; set; }
        public virtual DbSet<FriendList> FriendListSet { get; set; }
    }
}
